export type CampoProducto =
  | 'codigo'
  | 'nombre'
  | 'precio_costo'
  | 'precio_venta'
  | 'stock_actual'
  | 'stock_minimo'
  | 'categoria'
  | 'proveedor'
  | 'fecha_vencimiento'
  | 'unidad';

/** Diccionario de aliases por campo (60+ entradas en total). */
export const ALIASES: Record<CampoProducto, string[]> = {
  codigo: [
    'codigo',
    'cod',
    'code',
    'sku',
    'ref',
    'referencia',
    'art',
    'articulo',
    'id_producto',
    'cod_art',
    'codart',
    'item',
    'id',
    'codigointerno',
    'codinterno',
    'nroparte',
    'barras',
    'ean',
    'upc',
    'nroart',
    'codfabricante',
  ],
  nombre: [
    'nombre',
    'descripcion',
    'producto',
    'item',
    'articulo',
    'detalle',
    'desc',
    'name',
    'denominacion',
    'titulo',
    'glosa',
    'detalles',
    'descripcionlarga',
    'descripcionproducto',
  ],
  precio_costo: [
    'costo',
    'precio_costo',
    'pcosto',
    'costo_unitario',
    'precio_compra',
    'cost',
    'neto',
    'pc',
    'preciocompra',
    'valorcosto',
    'costounit',
    'cunit',
  ],
  precio_venta: [
    'precio',
    'pvp',
    'precio_venta',
    'pventa',
    'precio_unitario',
    'punit',
    'valor',
    'price',
    'venta',
    'precio_lista',
    'lista',
    'preciounit',
    'preciounitario',
    'pfinal',
    'pvpfinal',
    'ppublico',
    'importe',
    'tarifa',
  ],
  stock_actual: [
    'stock',
    'cantidad',
    'cant',
    'qty',
    'existencia',
    'disponible',
    'saldo',
    'inventario',
    'stockdisponible',
    'inv',
    'cantstock',
    'exist',
  ],
  stock_minimo: [
    'stock_minimo',
    'minimo',
    'min',
    'punto_pedido',
    'reposicion',
    'stmin',
    'minstock',
    'stockmin',
    'pedido',
    'repos',
  ],
  categoria: [
    'categoria',
    'cat',
    'rubro',
    'familia',
    'tipo',
    'category',
    'grupo',
    'linea',
    'seccion',
    'clasificacion',
    'depto',
    'departamento',
  ],
  proveedor: [
    'proveedor',
    'prov',
    'fabricante',
    'marca',
    'supplier',
    'distribuidor',
    'vendor',
    'provee',
  ],
  fecha_vencimiento: [
    'vencimiento',
    'vto',
    'venc',
    'expira',
    'caducidad',
    'fecha_venc',
    'expiry',
    'fvto',
    'fechavto',
    'vencim',
    'vencimientofecha',
  ],
  unidad: ['unidad', 'um', 'medida', 'unit', 'uom', 'umed', 'med', 'unmed', 'unid'],
};
